browser:
  browserName: chrome
  wait: 5
data:
  definedProduct: hummingbird
  currency: $
  minPriceRange: 9
  maxPriceRange: 10
  filterTestCategory: art
  onSaleHeader: ON SALE
  registrationPage: http://146.59.32.4/index.php?controller=authentication&create_account=1
  registeredUserUrl: http://146.59.32.4/index.php
  signOutText: Sign out
  numberOfCalculationRuns: 5
environment:
  test:
    envName: test
    active: true
    url: http://146.59.32.4/index.php

  prod:
    envName: test
    active: false
    url: http://146.59.32.4/index.php
